{% set version = "9.0.0" %}

package:
  name: scine-utilsos
  version: {{ version }}

source:
  - git_url: https://github.com/qcscine/utilities
    git_rev: '{{ version }}'
    patches:
      - patches/0001-skip-some-tests-on-osx.patch   # [osx]
      - patches/0002-add-missing-header-for-using-std-unique_ptr.patch

build:
  number: 0
  skip: true  # [win]

  run_exports:
    - {{ pin_subpackage('scine-utilsos', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - pkg-config
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - libboost-devel
    - eigen
    - gtest
    - gmock
    - lbfgspp
    - libblas
    - liblapack
    - scine-core
    - yaml-cpp
  run:
    - yaml-cpp

test:
  commands:
    - test -f $PREFIX/lib/libutilsos${SHLIB_EXT}

about:
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: |
    Contains functionality which is used in most SCINE modules.
  home: https://scine.ethz.ch/
  dev_url: https://github.com/qcscine/utilities

extra:
  recipe-maintainers:
    - awvwgk
    - ltalirz
    - matt-chan
